name: flutter_architecture_showcase
description: A Flutter project demonstrating various architecture patterns and state management techniques.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.3
  riverpod: ^2.4.9
  provider: ^6.1.1
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  equatable: ^2.0.5 
  flutter_riverpod: ^2.4.9
  uuid: ^4.0.0       # For generating unique IDs
  freezed_annotation: ^2.4.1 # Optional: For immutable state classes (recommended with Riverpod)
  
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Network
  http: ^1.2.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
